baseURL: http://thinkstack.io/
languageCode: en-GB
title: "Think Stack Limited"
theme: "toha"

# Allow raw html in markdown file
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

# Enable global emoji support
enableEmoji: true

# Custom parameters
params:
  # Copyright Notice
  copyright: © 2020 Copyright.

  # Meta description for your site.  This will help the search engines to find your site.
  description: Think Stack Limited Portal and Portfolio.

  # background image of the landing page
  background: "images/background.jpg"

  # Provide logos for your site. The inverted logo will be used in the initial
  # transparent navbar and the main logo will be used in the non-transparent navbar.
  # It will be default to the theme logos if not provided.
  logo:
    main: images/main-logo.png
    inverted: images/inverted-logo.png

  # GitHub repo URL of your site
  gitRepo: https://github.com/thinkstack/www-thinkstack-io

  # specify whether you want to write blog post or not
  enableBlogPost: true

  # specify whether you want to show Table of Contents in reading page
  enableTOC: true

  # Provide newsletter configuration. This feature hasn't been implemented yet.
  # Currently, you can just hide it from the footer.
  newsletter:
    enable: false

  # some information about you
  author:
    name: "Lee Myring"
    nickname: "Think:Stack"
    image: "images/avatar.png"
    # greeting message before your name. it will default to "Hi! I am" if not provided
    greeting: "We are"
    # give your some contact information. they will be used in the footer
    contactInfo:
      email: "mail@thinkstack.io"
      phone: "+447495771371"
    # a summary of what you do
    summary:
      - We are a DevOps consultantancy
      - We will work with you to deliver reduced time-to-market solutions
      - We work with many, varied cloud technologies
